id: P7004FB2B
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Tenpe Nyima Series
  language: zh
  description: 'Texts by and about the Third Dodrupchen, Jigme Tenpe Nyima (rdo grub
    chen ''jigs med bstan pa''i nyi ma, 1865–1926):'
  volume:
    74c8fecafd664eedbfebafe5e21b1e85:
      title: Advice for a Dying Practitioner
      parent: Advice
    86e0e140ec404d23b688feeddc688b0b:
      title: On Seeing the Guru as a Buddha
      parent: Advice
    530b9c8668a34de4a131b9cf38255fba:
      title: On Sleep
      parent: Advice
    e012c4b129084d22aac1aca468eee59a:
      title: On the Ignorance of the Learned
      parent: Advice
    4585943883aa4ad4b5db26eb943dc09a:
      title: Retreat Advice
      parent: Advice
    b8f94d1bfb9c48f19fb2bccee8c9cd03:
      title: Three Ways of Bringing Sickness onto the Path
      parent: Advice
    47b3811276c54e5290a00d4c3cb1455c:
      title: Turning Suffering & Happiness Into Enlightenment
      parent: Advice
    836bf387c7c947ac968b6352a352806d:
      title: Aspiration for Rebirth in Sukhāvatī
      parent: Aspiration Prayers
    17f899d15666476eab681c8f59daac31:
      title: Aspirations in Accordance with the Dharma
      parent: Aspiration Prayers
    244d2733cf78477fab68b38d33a94d0a:
      title: A Guide to the Practice of Sang
      parent: Commentaries
    8be9c8096ef44c1faad3e5961acf7162:
      title: A Simple Visualization for the Seven-Line Prayer
      parent: Commentaries
    b7e93c433d9446d5a54c45912a2fac70:
      title: 'Garland of Night-Blooming Water Lilies: A Commentary on the Guru Siddhi
        Mantra'
      parent: Commentaries
    69845b59ff4b40238f9fdd65af24c18e:
      title: 'Lamp That Illuminates the Excellent Path of Great Bliss: A Guide to
        the Practice Text of the Female Awareness-Holder, the Queen of Great Bliss'
      parent: Commentaries
    43852c3cd9454f7c986992d986b1224b:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    6dea3eb08fdd4619b732e47f5b871919:
      title: Teaching on the Offering of Flowers
      parent: Commentaries
    8e5b31c00a514c50ba1098decc51a8e4:
      title: Advice for Hor Özer
      parent: Dzogchen
    b96d236e187144f383693ec909424ef3:
      title: Advice for Palseng
      parent: Dzogchen
    39e27bcee82f4555bcf0f09792149ef6:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Dzogchen
    cb4f13507226463fad594325294b8346:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    36429c87b2d7486995faf228f4b393df:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    e8b21c53b24a4af0989333c4d6d0c808:
      title: 'Rain of Siddhis: A Prayer to the Lineage of Rigdzin Düpa'
      parent: Lineage Prayers
    2a7dd58ece0641318faf93140c7767ac:
      title: A Brief Ritual for Consecrating Representations of Enlightened Body,
        Speech and Mind
      parent: Practices
    bcf101372f32492d8d054a39caf79769:
      title: Rigdzin Düpa Amṛta Offering
      parent: Practices
    18d56383a6d046ca9f201088f49f2b1b:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Practices
    38635d0a390440dba579d8a9a1058cd0:
      title: Yumka Fulfilment Practice
      parent: Practices
    31a640d455c64092b4bb152614567d7b:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    41821417c69642518ee5a4af4e7a0e3d:
      title: In Praise of Sönam Palge
      parent: Praise
    ed6c76e156804863b0bc47ceaa7d38d2:
      title: Prayer to Ārya Tārā
      parent: Prayers
    8e2ed980f68a43c7bdf6ccbea1cd0215:
      title: Prayer to Avalokiteśvara
      parent: Prayers
    09777869e5bd4174ae506ce5b3a6f42e:
      title: Prayer to Buddha Amitābha
      parent: Prayers
    9a63142d3dbf4262a1fec694affc44da:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Prayers
    344549996be940548f3fec190d6bea2f:
      title: 'Words of the Vajra Queen: An Essential Daily Practice of the Vidyādharas’
        Female Practice'
      parent: Sādhanas
created_at: '2022-02-28T22:58:39.868606'
last_modified_at: '2022-02-28T22:58:39.868609'
